### ISSUE TITLE
Facing Error while running EffectiveMass

### ISSUE THREAD

**Issue by sajidurehman** [liujiacode/EffectiveMass#1]
Hi liujia,
i am a CASTEP user. please help to execute this code properly. i did following steps.
Step1: Generate Si band structure from Analysis option in Materials studio. 
Step2: Copy Si.xsd and Si.xcd (rename from Si band structure.xcd to Si.xcd ) files to Si folder.
Step3: Then execute "python EffectiveMass.py -p "/home/sajid/soft/EffectiveMass-master/Si" .
But i got following error. please guide me how to fix this error.

 Traceback (most recent call last):
  File "EffectiveMass.py", line 670, in <module>
    em = EffectiveMass(project_directory)
  File "EffectiveMass.py", line 157, in __init__
    self._code = self._project_name.split(' ')[-2]
IndexError: list index out of range

Looking forward to your king help

**Comment by liujiacode** [comment]
Thanks for your question. Firstly, there is no necessary to create a new folder (such as "Si" folder) to run this script. CASTEP would create **"XXX CASTEP GeomOpt"** automatically after geometry optimization (or **"XXX CASTEP Energy"** after energy calculation). You just need to run
 `python EffectiveMass.py -p "/path/to/XXX CASTEP GeomOpt" (or "/path/to/XXX CASTEP Energy")`
and the results file **"XXX Effective Mass.out"** would be generated automatically in this project directory.

Secondly, there is no necessary to rename the band structure files. The default names of xsd and xcd files are **"XXX.xsd"** and **"XXX Band Structure.xcd"**. If you want to use "Si.xcd" or "Si Band Structure (2).xcd", please use '-c' option as follow:
`python EffectiveMass.py -p "/path/to/Si CASTEP GeomOpt" -c "Si.xcd" (or "Si Band Structure (2).xcd")`

Hope this will be helpful you.

PS: In fact, "CASTEP" (or "DMol3") and "GeomOpt" (or "Energy") are keywords which should be contained as the ending of project directory name. For example, **"Si CASTEP Geometry"** is okay, but "Si", "Si CASTEP", "Si Geometry" or "Si CASTEP Geometry (2)", etc. can't be recognized by this script.

PPS: This script wouldn't change any existing files but only add a new file named "XXX Effective Mass.out" in your project folder. So, although is okay to create a new project directory and retain the original folder 'unchanged', running this script on the original project folder directly is still the most convenient way.

**Comment by sajidurehman** [comment]
Hi liujiacode,
Thank you so much for your kind reply. i followed your steps as you told me in above reply. but still i am getting error. please guide me what is i am going wrong this time.

sajid@ubuntu:~/soft/EffectiveMass-master$ **python EffectiveMass.py -p "/home/sajid/soft/EffectiveMass-master/Si CASTEP GeomOpt"**
Traceback (most recent call last):
  File "EffectiveMass.py", line 671, in <module>
    c_paras, k_paras, b_paras = em.load(xsd_file=model_xsd_file, bs_xcd_file=bandstr_xcd_file)
  File "EffectiveMass.py", line 202, in load
    raise ValueError("Too many(little) 'SpaceGroup' patterns: %s" % xsd_file)
ValueError: Too many(little) 'SpaceGroup' patterns: /home/sajid/soft/EffectiveMass-master/Si CASTEP GeomOpt/Si.xsd

Output file information 

Electron and hole effective mass calculated by /home/sajid/soft/EffectiveMass-master.
EffectiveMass.py Version: v1.01.2.
Project: /home/sajid/soft/EffectiveMass-master/Si CASTEP GeomOpt.
Code: CASTEP
Method: GeomOpt

**Comment by liujiacode** [comment]
This script doesn't support models without a certain space group or with two or more space groups. Please check the space group settled in Si.xsd. Generally each model file contains only one crystal (one space group) and I have no idea about what's wrong with your models. Maybe you have built too many crystals in one model file or maybe you have once changed the crystal and Materials Studio reserved the invalid messages of the old crystal in Si.xsd.

Open Si.xsd with text editor (such as vim or Notepad++ instead of Materials Studio) and search **"SpaceGroup"**. The best way to solve this problem is to rebuild this model if there are two or more tags like **"\<SpaceGroup ID=... ... /\>"** in Si.xsd.

Hope this message will be helpful to you.
