### ISSUE TITLE
Example Files

### ISSUE THREAD

**Issue by sajidurehman** [liujiacode/EffectiveMass#3]
Hi Dear,
            i tried everything which you told me but still i am unable to run it properly. Could it possible you can add example files for testing then it will be very helpful.

looking forward to your kind response 

Best Reagrds
Sajid

**Comment by liujiacode** [comment]
Hi Sajid,
Sorry for that I didn't replay to your issue in time. Thanks for your advice. Examples will be added later.

Best wishes
Liu Jia

**Comment by sajidurehman** [comment]
Thank you for reply. I will be waiting anxiously for addition of examples
